# Generated by Django 4.0.3 on 2022-10-13 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testr', '0002_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='course',
            name='enroll_password',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
