# Generated by Django 4.0.3 on 2022-10-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testr', '0008_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cpu_limit',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='question',
            name='memory_limit',
            field=models.FloatField(default=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit_seconds',
            field=models.FloatField(default=30),
        ),
    ]
