# Generated by Django 4.0.3 on 2022-11-05 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testr', '0009_question_cpu_limit_question_memory_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['student']},
        ),
        migrations.AlterModelOptions(
            name='evaluationinputoutput',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='evaluationinputoutput',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
