# Generated by Django 4.0.3 on 2022-10-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetest', '0003_alter_question_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.TextField(choices=[('CC', 'C/C++'), ('PT', 'Python')], default='PT', max_length=2),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.TextField(choices=[('WE', 'Waiting Evaluation'), ('FL', 'Fail'), ('SC', 'Success')], default='WE', max_length=2),
        ),
    ]
