# Generated by Django 4.0.3 on 2022-10-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetest', '0004_alter_question_description_alter_question_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluationscript',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evaluationinputoutput',
            name='input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evaluationinputoutput',
            name='output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evaluationinputoutput',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
