# Generated by Django 4.0.3 on 2022-10-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetest', '0005_course_visible_evaluationscript_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit_seconds',
            field=models.FloatField(default=10),
        ),
    ]
